# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: casaos-gateway
before:
  hooks:
    - go run github.com/google/go-licenses@latest check . --disallowed_types=restricted
    - go mod tidy
    - go test -v ./...
builds:
  - id: casaos-gateway-amd64
    binary: build/sysroot/usr/bin/casaos-gateway
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
    ldflags:
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - find build/sysroot -type f | xargs -L 1 realpath --relative-to=build/sysroot > build/sysroot.manifest
  - id: casaos-gateway-arm64
    binary: build/sysroot/usr/bin/casaos-gateway
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    ldflags:
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
    goos:
      - linux
    goarch:
      - arm64
    hooks:
      post:
        - find build/sysroot -type f | xargs -L 1 realpath --relative-to=build/sysroot > build/sysroot.manifest
  - id: casaos-gateway-arm-7
    binary: build/sysroot/usr/bin/casaos-gateway
    env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabihf-gcc
    ldflags:
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "7"
    hooks:
      post:
        - find build/sysroot -type f | xargs -L 1 realpath --relative-to=build/sysroot > build/sysroot.manifest
  - id: casaos-gateway-migration-tool-amd64
    binary: build/sysroot/usr/bin/casaos-gateway-migration-tool
    main: ./cmd/migration-tool
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
    ldflags:
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
    goos:
      - linux
    goarch:
      - amd64
  - id: casaos-gateway-migration-tool-arm64
    binary: build/sysroot/usr/bin/casaos-gateway-migration-tool
    main: ./cmd/migration-tool
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    ldflags:
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
    goos:
      - linux
    goarch:
      - arm64
  - id: casaos-gateway-migration-tool-arm-7
    binary: build/sysroot/usr/bin/casaos-gateway-migration-tool
    main: ./cmd/migration-tool
    env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabihf-gcc
    ldflags:
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "7"
archives:
  - name_template: "{{ .Os }}-{{ .Arch }}-{{ .ProjectName }}-v{{ .Version }}"
    id: casaos-gateway
    builds:
      - casaos-gateway-amd64
      - casaos-gateway-arm64
      - casaos-gateway-arm-7
    replacements:
      arm: arm-7
    files:
      - build/**/*
  - name_template: "{{ .Os }}-{{ .Arch }}-{{ .ProjectName }}-migration-tool-v{{ .Version }}"
    id: casaos-gateway-migration-tool
    builds:
      - casaos-gateway-migration-tool-amd64
      - casaos-gateway-migration-tool-arm64
      - casaos-gateway-migration-tool-arm-7
    replacements:
      arm: arm-7
    files:
      - build/sysroot/etc/**/*
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: IceWhaleTech
    name: CasaOS-Gateway
  draft: true
  prerelease: auto
  mode: replace
  name_template: "v{{ .Version }}"
